### ISSUE TITLE
호출 데이터 추출

### ISSUE THREAD

**Issue by BoBinLee** [Nexters/flass#25]

**Comment by BoBinLee** [comment]
상세 내역
비디오 영역 : title ( 컨텐츠 제목 ), videoUrl ( URL 주소 ), replayAt ( 재생 화면 위치 )
질문 등록 : myProfileUrl ( 자기프로필 URL )
질문 아이템 : questionId ( 질문아이디 ), content ( 질문내용 ), questionAt ( 질문시간 ), answers ( 답리스트 ), answerType ( 질문타입 )
     - 답아이템 : answerId ( 답아이디 ), 
코멘트
코멘트 등록 : userId ( 유저 아이디 ), myProfileUrl ( 자기프로필 URL )
코멘트 아이템 : userId ( 유저 아이디 ), userName ( 유저네임 ), profileUrl ( 프로필 URL ), content ( 내용 ), createdAt ( 등록날짜 ), updatedAt ( 업뎃날짜 )
분석
분석 아이템 : questionId ( 질문 아이디 ), content ( 질문내용 ), questionAt ( 질문시간 ), answers, answerType
     - 답아이템 : answerId ( 답아이디 ),

**Comment by yayshine** [comment]
업로드

- 비디오 등록: title ( 컨텐츠 제목 ), description ( 학습 목표 ), videoUrl ( URL 주소 ), thumbnail ( 썸네일 URL )
- 질문 아이템 : questionId ( 질문아이디 ), content ( 질문내용 ), questionAt ( 질문시간 ), answers ( 답리스트 ), answerType ( 답타입 ), hint ( 힌트 )
    - 답아이템 : answerId ( 답아이디 ), content ( 답내용 )
    - 힌트아이템 : hintId ( 힌트아이디 ), content ( 힌트내용 )
- 비디오 정보: length ( 비디오 길이 )
